FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY ["src/Dictionary/Admission.Dictionary/Admission.Dictionary.csproj", "src/Dictionary/Admission.Dictionary/"]
COPY ["src/MessagingContracts/MailContracts/MailContracts.csproj", "src/MessagingContracts/MailContracts/"]

RUN dotnet restore "src/Dictionary/Admission.Dictionary/Admission.Dictionary.csproj"

COPY ["src/Dictionary/Admission.Dictionary/", "src/Dictionary/Admission.Dictionary/"]
COPY ["src/MessagingContracts/MailContracts/", "src/MessagingContracts/MailContracts/"]

WORKDIR /src/src/Dictionary/Admission.Dictionary
RUN dotnet publish "Admission.Dictionary.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends wget \
    && rm -rf /var/lib/apt/lists/*

ENV ASPNETCORE_URLS=http://+:8080

EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Admission.Dictionary.dll"]