// <auto-generated />
using System;
using Admission.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Admission.Persistence.Migrations
{
    [DbContext(typeof(AdmissionDbContext))]
    [Migration("20260521205215_DropUniquePriorityConstraint")]
    partial class DropUniquePriorityConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Admission.Domain.Entities.Admission", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AdmissionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("applicant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("manager_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.HasIndex("applicant_id")
                        .IsUnique();

                    b.HasIndex("manager_id");

                    b.ToTable("admissions", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.AdmissionProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("admission_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("program_id");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.HasIndex("AdmissionId", "Priority");

                    b.ToTable("admission_programs", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Dictionary.EducationDocumentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("education_level_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("education_level_id");

                    b.ToTable("education_document_types", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Dictionary.EducationLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("education_levels", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Dictionary.EducationProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<string>("EducationForm")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("education_form");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("name");

                    b.Property<int>("education_level_id")
                        .HasColumnType("integer");

                    b.Property<Guid>("faculty_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("education_level_id");

                    b.HasIndex("faculty_id");

                    b.ToTable("education_programs", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Dictionary.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("faculties", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.EducationalDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("applicant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("education_document_type_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("file_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("applicant_id")
                        .IsUnique();

                    b.HasIndex("education_document_type_id");

                    b.HasIndex("file_id")
                        .IsUnique();

                    b.ToTable("educational_documents", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Passport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("GivenBy")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("given_by");

                    b.Property<DateTime>("GivenDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("given_date");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("serial_number");

                    b.Property<Guid>("applicant_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("file_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("applicant_id")
                        .IsUnique();

                    b.HasIndex("file_id")
                        .IsUnique();

                    b.ToTable("passports", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("education_document_type_next_levels", b =>
                {
                    b.Property<Guid>("education_document_type_id")
                        .HasColumnType("uuid");

                    b.Property<int>("next_education_level_id")
                        .HasColumnType("integer");

                    b.HasKey("education_document_type_id", "next_education_level_id");

                    b.HasIndex("next_education_level_id");

                    b.ToTable("education_document_type_next_levels", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Applicant", b =>
                {
                    b.HasBaseType("Admission.Domain.Entities.User");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Citizenship")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("citizenship");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.ToTable("applicants", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Manager", b =>
                {
                    b.HasBaseType("Admission.Domain.Entities.User");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<Guid?>("FacultyId")
                        .HasColumnType("uuid")
                        .HasColumnName("faculty_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasIndex("FacultyId");

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("Admission.Domain.Entities.Admission", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Manager", null)
                        .WithMany("Admissions")
                        .HasForeignKey("ManagerId");

                    b.HasOne("Admission.Domain.Entities.Applicant", "Applicant")
                        .WithOne("Admission")
                        .HasForeignKey("Admission.Domain.Entities.Admission", "applicant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admission.Domain.Entities.Manager", "Manager")
                        .WithMany("_admissionsList")
                        .HasForeignKey("manager_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Applicant");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Admission.Domain.Entities.AdmissionProgram", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Admission", "Admission")
                        .WithMany("AdmissionPrograms")
                        .HasForeignKey("AdmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admission.Domain.Entities.Dictionary.EducationProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admission");

                    b.Navigation("Program");
                });

            modelBuilder.Entity("Admission.Domain.Entities.Dictionary.EducationDocumentType", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Dictionary.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("education_level_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EducationLevel");
                });

            modelBuilder.Entity("Admission.Domain.Entities.Dictionary.EducationProgram", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Dictionary.EducationLevel", "EducationLevel")
                        .WithMany()
                        .HasForeignKey("education_level_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Admission.Domain.Entities.Dictionary.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("faculty_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EducationLevel");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Admission.Domain.Entities.EducationalDocument", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Applicant", "Applicant")
                        .WithOne("EducationalDocument")
                        .HasForeignKey("Admission.Domain.Entities.EducationalDocument", "applicant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admission.Domain.Entities.Dictionary.EducationDocumentType", "EducationDocumentType")
                        .WithMany()
                        .HasForeignKey("education_document_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Admission.Domain.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("Admission.Domain.Entities.EducationalDocument", "file_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Applicant");

                    b.Navigation("EducationDocumentType");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Admission.Domain.Entities.Passport", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Applicant", "Applicant")
                        .WithOne("Passport")
                        .HasForeignKey("Admission.Domain.Entities.Passport", "applicant_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admission.Domain.Entities.File", "File")
                        .WithOne()
                        .HasForeignKey("Admission.Domain.Entities.Passport", "file_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Applicant");

                    b.Navigation("File");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("education_document_type_next_levels", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Dictionary.EducationDocumentType", null)
                        .WithMany()
                        .HasForeignKey("education_document_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Admission.Domain.Entities.Dictionary.EducationLevel", null)
                        .WithMany()
                        .HasForeignKey("next_education_level_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Admission.Domain.Entities.Manager", b =>
                {
                    b.HasOne("Admission.Domain.Entities.Dictionary.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Admission.Domain.Entities.Admission", b =>
                {
                    b.Navigation("AdmissionPrograms");
                });

            modelBuilder.Entity("Admission.Domain.Entities.Applicant", b =>
                {
                    b.Navigation("Admission");

                    b.Navigation("EducationalDocument");

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("Admission.Domain.Entities.Manager", b =>
                {
                    b.Navigation("Admissions");

                    b.Navigation("_admissionsList");
                });
#pragma warning restore 612, 618
        }
    }
}
