<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Admission.Application\Admission.Application.csproj" />
    </ItemGroup>

</Project>
